default: &default
  name: koechi
  cdn_url: https://cdn.koechi.com
  client_url: http://localhost:3000
    
development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  client_url: https://koechi.com
