default: &default
  name: koechi
  cdn_url: https://cdn.koechi.com
  client_url: http://localhost:3000
  per_page_search: 48
  per_page_talk: 48
  per_page_follower: 36
  per_page_following: 36
  per_page_comment: 24
  per_page_like: 36
  per_page_note: 48
  per_page_space_note: 36
    
development:
  <<: *default
  

test:
  <<: *default

production:
  <<: *default
  client_url: https://koechi.com
